### ISSUE TITLE
Problems with running

### ISSUE THREAD

**Issue by DongChen06** [koryakinp/mldriver-discrete-steering#1]
Hi author, I ran the code [https://github.com/koryakinp/A2C](url), I modified the environment and just want to test it on the gym environment such as pong. While I got the **_NotImplementedError_** error like the below code. Do you have any ideas about that, thanks.

```Model is built successfully


Training...
WARNING:tensorflow:From /home/dong/Downloads/A2C/base_train.py:28: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2020-03-21 21:05:04.948890: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
No checkpoints available!


Process Process-1:
Traceback (most recent call last):
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dong/Downloads/A2C/envs/subproc_vec_env.py", line 19, in worker
    ob = env.reset()
  File "/home/dong/Downloads/A2C/envs/gym_env.py", line 28, in reset
    return self.env.reset()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 272, in reset
    return self.env.reset(**kwargs)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 260, in reset
    return self.observation(observation)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 267, in observation
    raise NotImplementedError
NotImplementedError
Process Process-4:
Traceback (most recent call last):
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dong/Downloads/A2C/envs/subproc_vec_env.py", line 19, in worker
    ob = env.reset()
  File "/home/dong/Downloads/A2C/envs/gym_env.py", line 28, in reset
    return self.env.reset()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 272, in reset
    return self.env.reset(**kwargs)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 260, in reset
    return self.observation(observation)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 267, in observation
    raise NotImplementedError
NotImplementedError
Process Process-3:
Traceback (most recent call last):
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dong/Downloads/A2C/envs/subproc_vec_env.py", line 19, in worker
    ob = env.reset()
  File "/home/dong/Downloads/A2C/envs/gym_env.py", line 28, in reset
    return self.env.reset()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 272, in reset
    return self.env.reset(**kwargs)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 260, in reset
    return self.observation(observation)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 267, in observation
    raise NotImplementedError
NotImplementedError
Process Process-2:
Traceback (most recent call last):
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dong/Downloads/A2C/envs/subproc_vec_env.py", line 19, in worker
    ob = env.reset()
  File "/home/dong/Downloads/A2C/envs/gym_env.py", line 28, in reset
    return self.env.reset()
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 272, in reset
    return self.env.reset(**kwargs)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 260, in reset
    return self.observation(observation)
  File "/home/dong/anaconda3/envs/py3.5/lib/python3.5/site-packages/gym/core.py", line 267, in observation
    raise NotImplementedError
NotImplementedError```

**Comment by koryakinp** [comment]
Hey @Derekabc, I think you are running a code from that repo: https://github.com/MG2033/A2C (which is much better implementation of A2C btw), you probably should ask your question there.
